@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()

Person(customer, "Клиент", "Пользуется сайтом и интернет-банком")

System_Boundary(bank_system, "Банковская система") {

    Container(web, "Веб-сайт", "PHP/React.js", "Для новых клиентов: просмотр депозитов и кредитов, подача заявок")
    Container(ib, "Интернет-банк", ".NET Framework 4.5/MSSQL", "Для действующих клиентов: депозиты, кредиты, предодобренные предложения")

    Container(notify, "Notification Service", "Internal SMS Core", "Отправка SMS-кодов и уведомлений")

    ContainerDb(db, "Databases", "MS SQL / Oracle", "Хранение заявок и клиентских данных")

    Container_Ext(abs, "ABS", "Core Banking", "Хранение и подтверждение депозитов и кредитов")
    Container_Ext(conveyor, "Credit Conveyor", "Internal", "Полная информация об условиях кредитов")
    Container_Ext(scoring, "Scoring System", "Internal", "Скоринг клиентов, интеграция с БКИ")
    Container(backoffice, "Back-office", "", "Менеджеры в офисе")
    Container(frontoffice, "Front-office", "", "Менеджеры в бэк офисе")
}

Rel(customer, web, "Просмотр депозитов/кредитов, подача заявки")
Rel(customer, ib, "Управление депозитами и кредитами")

Rel(frontoffice, abs, "Работа с депозитами/кредитами")
Rel(frontoffice, backoffice, "Работа с депозитами/кредитами")
Rel(customer, frontoffice, "Работа с депозитами/кредитами")

Rel(backoffice, abs, "Работа с депозитами/кредитами")
Rel(backoffice, conveyor, "Работа с условиями кредитов")
Rel(backoffice, scoring, "Работа с условиями кредитов")

Rel(abs, db, "Работа с условиями кредитов")
Rel(abs, notify, "Оповещение клинтов")

@enduml
